import 'cross-fetch/polyfill'
import {GaiaHubConfig, generateGaiaHubConfig, putFile, PutFileOptions} from 'micro-stacks/storage';

//This module is for Trubit's specific use cases, with hardcode Trubit info:
// 1. Get a Trubit app Gaia storage object.
// 2. Create a Trubit app user Gaia file.
// 3. Read a Trubit app user Gaia file.
// 4. Update a Trubit app user Gaia file.
// 5. List all Trubit app user Gaia files.

// Return a (Promise) Gaia object
async function getStorage(privateKey: string): Promise<void> {
    const gaiaHubConfig: GaiaHubConfig = await generateGaiaHubConfig({
        privateKey,
        gaiaHubUrl: 'https://hub.blockstack.org'
    })
    //console.log('yyy', gaiaHubConfig);
}

async function run() {
    const path = 'file2.json';
    const privateKey = '2e0f1b1b5b2dd054fcc176d5b8e82e0425cec26e555d108298a7e16a8853e7a9';

    const gaiaHubConfig: GaiaHubConfig = await generateGaiaHubConfig({
        privateKey,
        gaiaHubUrl: 'https://hub.blockstack.org'
    })
    const fileContent = JSON.stringify({'interest': 'skiing', 'age': 22, 'gender': 'male'});
    const encryptOptions: PutFileOptions = {encrypt: false, gaiaHubConfig, privateKey};
    const publicURL = await putFile(path, fileContent, encryptOptions);
    console.log('xxx', publicURL);
    console.log('yyy', gaiaHubConfig);
}

//run().then(console.log).catch(console.error)

//where do i get the private of user? from session object?
const privateKey = '2e0f1b1b5b2dd054fcc176d5b8e82e0425cec26e555d108298a7e16a8853e7a9';
const aWhat = getStorage(privateKey);  //.then(console.log).catch(console.log);
console.log("asdf", aWhat);
/*
This is a generated Gaia hub config.  Note the public address and token generated by the function generateGaiaHubConfig()
{
    address: '19ipr3aK7BXxy3h4NfJxzoywxHqd8NhkYg',
    url_prefix: 'https://gaia.blockstack.org/hub/',
    token: 'v1:eyJ0eXAiOiJKV1QiLCJhbGciOiJFUzI1NksifQ.eyJnYWlhQ2hhbGxlbmdlIjoiW1wiZ2FpYWh1YlwiLFwiMFwiLFwic3RvcmFnZTIuYmxvY2tzdGFjay5vcmdcIixcImJsb2Nrc3RhY2tfc3RvcmFnZV9wbGVhc2Vfc2lnblwiXSIsImh1YlVybCI6Imh0dHBzOi8vaHViLmJsb2Nrc3RhY2sub3JnIiwiaXNzIjoiMDMyZDg2NGFmNGJhNDlhZGEyZTA0Yzg2MTRhYjY0N2NmYzVhOTMzODBiMTUzNWE4ODA4NWQ4MDgwMzljNGIwYjlkIiwic2FsdCI6IjQyLDI1LDI0NSw5Miw0OSw4NCwxODgsOTUsNzcsODksMTE4LDIwNCwxNjYsMTc3LDY5LDQ3IiwiYXNzb2NpYXRpb25Ub2tlbiI6bnVsbCwic2NvcGVzIjpudWxsfQ.FUm+uPIuRwkrk9tmj6X9a+L/gT3XE6gN4ZAn7HoVxjX3O2lEMjXqRLtIzkzjdM5I0hzHKoVF3dJUhDrGffLnCA',
    server: 'https://hub.blockstack.org',
    max_file_upload_size_megabytes: 20
}

Meaning, if I am not mistaken:
 - token is the authorization
 - url_prefix + address + path/filename is the complete uri
Point is, generate a GaiaHubConfig and pass the whole thing as parameter
*/

/*
Where is the appName specified?  i.e. Trubit app
*/