import 'cross-fetch/polyfill';
import { generateGaiaHubConfig, putFile } from 'micro-stacks/storage';
async function run() {
    const path = 'file2.json';
    const privateKey = '2e0f1b1b5b2dd054fcc176d5b8e82e0425cec26e555d108298a7e16a8853e7a9';
    const gaiaHubConfig = await generateGaiaHubConfig({
        privateKey,
        gaiaHubUrl: 'https://hub.blockstack.org'
    });
    const fileContent = JSON.stringify({ 'interest': 'skiing', 'age': 22, 'gender': 'male' });
    const encryptOptions = { encrypt: false, gaiaHubConfig, privateKey };
    const publicURL = await putFile(path, fileContent, encryptOptions);
    console.log('xxx', publicURL);
    console.log('yyy', gaiaHubConfig);
}
console.log(run().then(console.log).catch(console.error));
/*
This is a generated Gaia hub config.  Note the public address and token generated by the function generateGaiaHubConfig()
{
    address: '19ipr3aK7BXxy3h4NfJxzoywxHqd8NhkYg',
    url_prefix: 'https://gaia.blockstack.org/hub/',
    token: 'v1:eyJ0eXAiOiJKV1QiLCJhbGciOiJFUzI1NksifQ.eyJnYWlhQ2hhbGxlbmdlIjoiW1wiZ2FpYWh1YlwiLFwiMFwiLFwic3RvcmFnZTIuYmxvY2tzdGFjay5vcmdcIixcImJsb2Nrc3RhY2tfc3RvcmFnZV9wbGVhc2Vfc2lnblwiXSIsImh1YlVybCI6Imh0dHBzOi8vaHViLmJsb2Nrc3RhY2sub3JnIiwiaXNzIjoiMDMyZDg2NGFmNGJhNDlhZGEyZTA0Yzg2MTRhYjY0N2NmYzVhOTMzODBiMTUzNWE4ODA4NWQ4MDgwMzljNGIwYjlkIiwic2FsdCI6IjQyLDI1LDI0NSw5Miw0OSw4NCwxODgsOTUsNzcsODksMTE4LDIwNCwxNjYsMTc3LDY5LDQ3IiwiYXNzb2NpYXRpb25Ub2tlbiI6bnVsbCwic2NvcGVzIjpudWxsfQ.FUm+uPIuRwkrk9tmj6X9a+L/gT3XE6gN4ZAn7HoVxjX3O2lEMjXqRLtIzkzjdM5I0hzHKoVF3dJUhDrGffLnCA',
    server: 'https://hub.blockstack.org',
    max_file_upload_size_megabytes: 20
}
*/
/*
const publicURL = await putFile(path, fileContent, options);

export async function putFile(
    path: string,
    content: string | Uint8Array | ArrayBufferView | Blob,
    options: PutFileOptions
  ): Promise<string> {

    return await uploadFn(gaiaHubConfig);
*/ 
